controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

reservation:
    path: '/reservation/{id}'
    controller: App\Controller\ReservationController::reserver

    